/**
 * This file re-exports the auto-generated Supabase types.
 *
 * database.types.ts is NOT hand-written — it is generated by:
 *   pnpm db:types
 * (which runs `supabase gen types typescript` against the live schema)
 *
 * As of Milestone 3, this was generated against the live
 * `automated-ke-dev` Supabase project (all 9 Phase 1 migrations
 * applied), not hand-authored — see CLAUDE.md and RLS_Policy_Reference.md
 * for the verification history. Regenerate after every schema change and
 * commit the result; never hand-edit.
 */
export type { Database } from "./database.types";
